name: photo_note
description: A photo-centric daily note taking app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  intl: ^0.20.0
  path: ^1.8.3
  crypto: ^3.0.3
  file_picker: ^8.0.0
  archive: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
